# default paths
export XDG_CONFIG_HOME="$HOME/.config"

export PATH="$HOME/.local/bin:$PATH"

export GOPATH=$(go env GOPATH)
export GOBIN=$GOPATH/bin
export PATH="$PATH:$GOBIN"

export PATH="/usr/local/mysql/bin:$PATH"
export PATH="/opt/homebrew/opt/postgresql@17/bin:$PATH"
export PATH="/opt/homebrew/opt/sqlite/bin:$PATH"

export PATH="$HOME/.cargo/bin:$PATH"

export PATH="$HOME/development/flutter/bin:$PATH"
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"

export PATH="$HOME/.spicetify:$PATH"

export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

export VCPKG_ROOT="/opt/vcpkg"

export EDITOR=nvim
