# version: 1.0.0

format = """\
$hostname\
$directory\
$jobs\
$sudo\
$username \
 $character"""

right_format = """
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cpp\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$pixi\
$meson\
$spack\
$memory_usage\
$custom\
$status\
$os\
$battery \
 $time"""

continuation_prompt = "[▸▹ ](dimmed white)"

[fill]
symbol = ' '

[character]
format = "$symbol "
success_symbol = "[◎](bold italic bright-yellow)"
error_symbol = "[○](italic purple)"
vimcmd_symbol = "[■](italic dimmed green)"

[directory]
home_symbol = "⌂"
truncation_length = 2
truncation_symbol = "□ "
read_only = " ◈"
use_os_path_sep = true
style = "italic blue"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'bold blue'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) [△](bold bright-blue)'

[git_branch]
symbol = " "
style = "bold bright-green"
format = "[$symbol$branch]($style)"

[git_status]
style = "italic white"
format = "([$all_status]($style))"

[nodejs]
symbol = "⬢ "
format = "[$symbol$version](bold bright-green)"

[python]
symbol = " "
format = "[$symbol$version](bold yellow)"

[rust]
symbol = "🦀 "
format = "[$symbol$version](bold red)"

[lua]
symbol = "🌙 "
format = "[$symbol$version](bold bright-yellow)"

[package]
symbol = "📦 "
format = "[$symbol$version](dimmed italic)"

[cmd_duration]
format = "[⏱ $duration](dimmed white)"

[jobs]
format = "[⚙ $number](dimmed white)"
style = "white"

[memory_usage]
symbol = "💾"
format = "[$symbol $ram](dimmed white)"
disabled = false

[battery]
format = "[🔋$percentage$symbol](dimmed white)"
charging_symbol = "↑"
discharging_symbol = "↓"
full_symbol = "█"
disabled = false

[time]
disabled = false
time_format = "%H:%M"
format = "[$time](dimmed white)"

[status]
disabled = false
format = "[$status](bold red)"

